#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May  8 19:53:02 2022

@author: adelinelarente
"""


import numpy as np
import matplotlib.pyplot as plt


x0=1;y0=1 
#conditions initiales pour les proies et les prédateurs 
#(on commence avec 1 proie et 1 prédateur)

r=1;K=1;a=1;b=1;e=0.5;m=0.1
#fixe les valeurs des paramètres du modèle


def fonctions_gause_isoclines(x):
    
    global r,K,a,b,e,m  
    
    y= (a*x)
    
    return y

def fonctions_rosenzweig_mcarthur_isoclines(x):
    
    global r,K,a,b,e,m  
    
    y= (a*x)/(1+b*x)
    
    plt.plot (x,y)
    return y


x1=list(np.arange(0,5,0.01))
y1a=[]
y1b=[]
for xx in x1:
    yya=fonctions_gause_isoclines(xx)
    yyb=fonctions_rosenzweig_mcarthur_isoclines(xx)
    
    y1a=y1a+[yya]
    y1b=y1b+[yyb]
    
fig, graph = plt.subplots()
graph.plot(x1,y1a, 'k--', label='Taux de proies consommées pour le modèle de Gause')
graph.plot(x1,y1b, 'black', label='Taux de proies consommées pour le modèle de Rosenzweig-McArthur')
graph.set_xlabel('Proies')
graph.set_ylabel('Prédateurs')
graph.legend(title= 'Légende',bbox_to_anchor =(1.05, 1.3), ncol = 1)

